Selenium 3 changes
browserstack/php-selenium-browserstack pull request #2
Opened 2022-04-08 04:11 UTC by RutvikChandla

2022-04-09 11:00 UTC, asambstack requested changes

2022-04-09 11:01 UTC, asambstack commented on README.md
> +1. php and composer should be installed in your system
```suggestion
1. `php` and `composer` should be installed in your system
```

2022-04-11 05:24 UTC, RutvikChandla commented on README.md
> +3. Run tests
No, for parallel tests of PHP we recommend to use frameworks.

2022-04-11 05:30 UTC, RutvikChandla commented
@asambstack Please review.

2022-04-11 05:40 UTC, asambstack commented
Do we not have parallel tests for PHP?

2022-04-11 05:54 UTC, asambstack commented on README.md
> +3. Run tests
>Format this point, single test and local test should be sub-headings within point-3.

This isn't done. Make single and local tests as sub headings.

2022-04-12 04:41 UTC, RutvikChandla commented on README.md
> +3. Run tests
@asambstack is the recent change correct?

2022-04-18 05:42 UTC, asambstack reviewed
Readme changes

2022-04-18 05:42 UTC, asambstack commented on README.md
> +# php-selenium-browserstack
This line can be removed.

2022-04-18 05:42 UTC, asambstack commented on README.md
> +---
This divider can be removed.

2022-04-18 09:42 UTC, asambstack approved these changes
LGTM

2022-04-18 12:48 UTC, merged